version: '3.3'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    container_name: epcvip-server
    volumes:
       - ./server:/usr/app/server
       - /usr/app/server/node_modules
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: epcvip-client
    stdin_open: true
    tty: true
    volumes:
      - ./client:/usr/app/client
      - /usr/app/client/node_modules
    depends_on:
      - server