version: '3.3'
services:
  epcvip-server:
    build:
      context: ./server
    ports:
      - "3080:3080"
    container_name: epcvip-server
    volumes:
      - ./server:/usr/app/server
      - /usr/app/server/node_modules
    restart: always
  epcvip-client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    container_name: epcvip-client
    volumes:
      - ./client:/usr/app/client
      - /usr/app/client/node_modules
    # entrypoint: ["sh", "-c"]
    restart: always
    stdin_open: true
    tty: true
    environment: 
      - CHOKIDAR_USEPOLLING=true
      - CI=true
    depends_on:
      - epcvip-server
    # command: ["cp /tmp/yarn.lock yarn.lock & nodemon server.js & if [ '(tar -cf - /usr/local/share/.cache/yarn/v1 | crc32)' != '(tar -cf - .yarn_cache | crc32)' ]; then cp -r /usr/local/share/.cache/yarn/v1/. .yarn_cache/; fi"]
  tests:
    build:
      context: ./client
    volumes:
      - ./client:/usr/app/client
      - /usr/app/client/node_modules
    stdin_open: true
    tty: true
    command: ["yarn", "test"]